車の作成結果画面を作成
nose221834/ChatGP pull request #45
Opened 2024-03-08 09:21 UTC by AobaIwaki123

## 目的
車の作成結果画面を作成
## 概要
車の作成結果画面において以下が表示されるようにした
- 説明文
- 名前
- 調子
- 生成された画像

## 確認項目

- [ ] 車の作成後、`localhost:9004/create/result`に以下の画面が出てくることを確認する
<img width="1433" alt="image" src="https://github.com/nose221834/ChatGP/assets/52813844/c7e08d8e-e333-468d-81a1-8a5cdfde1e47">

## 不安・相談

2024-03-08 10:15 UTC, nose221834 requested changes
見た目はいい感じだね
考えてなかったんだけど、次の/raceに飛ぶボタンが無いとだめだから、どっかに配置して欲しい

2024-03-08 10:15 UTC, nose221834 commented on view/src/app/create/result/page.tsx
>    } else {
要らないコメントアウトは消そう

2024-03-08 10:15 UTC, nose221834 commented on view/src/lib/const.ts
> +};
1~6しか来ないようになってるの？

2024-03-08 10:15 UTC, nose221834 commented on view/src/app/create/result/page.tsx
> -      <div>
image以外もここで呼び出して、image以外もあるか判定した方が良さそう

2024-03-08 10:15 UTC, nose221834 commented on view/src/app/create/result/page.tsx
> +          </div>
1~6以外が帰ってきたときにこわれちゃうから、
事前に呼び出して、nullチェックした方が良さそう

2024-03-08 10:33 UTC, AobaIwaki123 commented on view/src/lib/const.ts
> +};
そうらしいよ

2024-03-08 11:48 UTC, AobaIwaki123 commented on view/src/app/create/result/page.tsx
>    } else {
忘れてた

2024-03-09 05:06 UTC, daikonoisii commented
問題なく操作できました

2024-03-09 05:07 UTC, daikonoisii approved these changes
good job!!!

2024-03-09 07:15 UTC, nose221834 approved these changes

2024-03-09 07:35 UTC, merged